### ISSUE TITLE
Issues with encoding of http-answers

### ISSUE THREAD

**Issue by Weyaaron** [webrecorder/warcio#142]
Dear Community,

thanks for providing this tool, I appreciate the ease of working with it. 
However, I stumbled upon an issue with encoding:
```
  for record in tqdm(ArchiveIterator(stream)):
                if record.rec_type == 'response':
                    target_url = record.rec_headers.get_header('WARC-Target-URI')
                    raw_body = record.raw_stream.read()
                    plaintext_body = str(raw_body, encoding="utf-8")
```
This code snippet results in Unicode-Decode-Errors. 
The data is straight from Commoncrawl, which suggests to me that the files are fine. 
Is there a way to verify this? 
I tried to use content_stream as well, to no avail. 
My goal is to decode all the responses properly. 
Since I am from germany, this is important since
we might encounter chars like "ä" or "ü", which need to be resolved properly. 
I did use https://www.crummy.com/software/BeautifulSoup/bs4/doc/#unicode-dammit
at times, but this seems a crude solution at best. 
What is the correct way of decoding payload of the answer-records? 

Greetings,
Aaron

**Comment by wumpus** [comment]
The web is a dangerous place, because many webservers will send you text that is encoded differently from what the webserver claims. The rules that browsers use to display data are very complicated. So it's easy to have a website that looks fine in your browser but is difficult to access from code.

If you are not too concerned with execution time, I would recommend using FTFY https://pypi.org/project/ftfy/

**Comment by Weyaaron** [comment]
This is working fine, thanks for the recommendation.
