### ISSUE TITLE
order of request/response pairs

### ISSUE THREAD

**Issue by tungol** [webrecorder/warcio#20]
Is there a reason why WARCWriter will output the response before the request when using write_request_response_pair? Wouldn't it be more natural to put the request first?

Very minor nitpick.

**Comment by wumpus** [comment]
Heretrix outputs the response before the request. I wonder how many warc tools break with the reverse ordering?

**Comment by nlevitt** [comment]
Writing them that way has been a convention for a long time. I think the reason is that the response record is considered the principal, and the request record sort of represents some extra information about it.

I don't think that wayback (openwayback, pywb, etc) care about the ordering of the records. They ignore the request records anyway afaik. Not sure about other tools.

**Comment by tungol** [comment]
Ah. I'd only generated warc records with wget before, which orders them as request then response. Interesting to hear that that's unusual!

**Comment by wumpus** [comment]
That's good to know about wget, that means that the Wayback Machine already has a fair amount of warc data in that form, thanks to Archive Team.

**Comment by ikreymer** [comment]
Yeah, pywb can support either request-response or response-request order. FWIW, CommonCrawl also generates data in request-response-metadata form. The request record is not always ignored however, as it can be used to resolve POST/PUT data into an index (pywb has an option to do this).

I'm planning to add a way to better reference concurrent records for improved indexing, though likely in a separate tool for indexing

**Comment by kartheek7895** [comment]
As there are no docs available on this, can someone explain how to use this request_response_pair feature?
