### ISSUE TITLE
Using print to report a warning or error seems brittle

### ISSUE THREAD

**Issue by anjackson** [webrecorder/warcio#31]
I've been attempting to use warcio in Hadoop streaming jobs. This went rather wrong because Hadoop streaming mode uses stdin/stdout and warcio prints to stdout under certain error conditions:

https://github.com/webrecorder/warcio/blob/ed7ebfd7c518bb6ff7e43bfc5d76285ea6eeb8b0/warcio/bufferedreaders.py#L142-L144

This seems brittle/clumsy. Surely this should raise an exception if it's serious, and/or using the standard logging framework (as appropriate)?

(Sadly, I still have not got to the bottom of why a WARC file that works fine when processed via `warcio index` managed to throw this error when processed via Hadoop, but that's a separate issue)

**Comment by ikreymer** [comment]
Agree the print statement here is an oversight (and the only one remaining in warcio).

The particular error condition is that part of the stream was decompressed, but later an error occurred. I recall the reason for not throwing the exception was to process what was read correctly, 
so that `read()` can still return as much valid data as possible, and then print out an error message. But the message should most certainly go to stderr and perhaps there should be 'strict' mode which interrupts the read altogether.

**Comment by anjackson** [comment]
In case anyone's interested, the issue is that the streaming mode on our old Hadoop cluster passes keys and values in separated by tabs and newlines. My code was breaking the binary stream into arbitrary chunks, and so the framework was injecting newlines between them, which of makes a mess of course.

I eventually managed to fix the code so it sent the whole file in, but that requires reading the whole file into memory first, and thus is rather brittle/clumsy (and led to timeouts, waiting for the mapper as it was giving no feedback while it was working). I'll probably change strategy.

**Comment by ikreymer** [comment]
Switched to writing to stderr, released in warcio 1.5.2
